name: CI-Back

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Back:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
                  
      - name: SCP files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "Back-end"
          target: "."

      - name: SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo rm -fr  Back-end/*/migrations
            cd Back-end/
            python3 -m venv env
            source env/bin/activate
            pip install -r requirements.txt
            pip install gunicorn
            python manage.py makemigrations
            python manage.py makemigrations
            python manage.py migrate
            kill -HUP $(lsof -i:8000 -t)

