name: CI

on:
  push:
    branches: [ frontend ]

  workflow_dispatch:

jobs:
  front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Front-end/frontend
    steps:
      - uses: actions/checkout@v2
      
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: Installs dependencies
        run: npm ci --legacy-peer-deps --production

      - name: Builds project
        run: npm run build
        
      - name: Uploads project
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./Front-end/frontend/build/
          server-dir: ./public_html/BSU/

